---
- name: "show remote environment"
  shell: env

- name: "copy zipped archive"
  become: true
  synchronize:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz
    recursive: true

- name: Create App directory
  file:
    path: ~/app
    state: directory

- name: Extract the zipped artifact
  shell: tar xzvf artifact.tar.gz --directory app

- name: Install dependencies
  args:
    chdir: /home/ubuntu/app
  shell: npm install

- name: "stop already running tasks"
  become: true
  ignore_errors: true
  command: pm2 stop default

- name: "start server"
  become: true
  args:
    chdir: /home/ubuntu/app
  shell: pm2 start npm -- start
