---
- name: "update packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: Install Python
  become: yes
  apt:
    name: python3

- name: "Install Packages"
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest

- name: "Install pm2"
  become: true
  npm:
    name: pm2
