rule_files:
  - /etc/prometheus/rules.yml

global:
  scrape_interval: 1s
  evaluation_interval: 1s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093
            - localhost:9093

scrape_configs:
  - job_name: "node"
    ec2_sd_configs:
      - region: us-east-1
        access_key: AKIAXEA4XEQ7VWVKV76F
        secret_key: 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
        port: 9100

  - job_name: "udapeople"
