route:
  group_by: [Alertname]
  group_wait: 10s
  group_interval: 2m
  repeat_interval: 1h
  receiver: email-me

  receivers:
    - name: email-me
      email_configs:
        - to: bwoyreezy22@gmail.com
          from: joshmensah18@gmail.com
          smarthost: smtp.gmail.com:587
          auth_username: joshmensah18@gmail.com
          auth_identity: joshmensah18@gmail.com
          auth_password: Josh_ua123
          send_resolved: true
inhibit_rules:
  - source_match:
      severity: "critical"
    target_match:
      severity: "warning"
    equal: ["alertname", "dev", "instance"]
