route:
  group_by: [Alertname]
  receiver: email-me

  receivers:
    - name: email-me
      email_configs:
        - to: jymensah004@st.ug.edu.gh
          from: joshmensah18@gmail.com
          smarthost: smtp.gmail.com:587
          auth_username: joshmensah18@gmail.com
          auth_identity: joshmensah18@gmail.com
          auth_password: Josh_ua123
