## ALERT MANAGER
- name: download and extract alert Manager
  become: true
  shell: |
    wget https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-0.21.0.linux-amd64.tar.gz
    tar xvfz alertmanager-0.21.0.linux-amd64.tar.gz

- name: install alert Manager
  become: yes
  shell: |
    cp alertmanager-0.21.0.linux-amd64/alertmanager /usr/local/bin
    cp alertmanager-0.21.0.linux-amd64/amtool /usr/local/bin/
    mkdir /var/lib/alertmanager
    rm -rf alertmanager*

- name: configure alert manager to send alerts
  become: yes
  template:
    src: files/alertmanager.yml
    dest: /etc/prometheus/alertmanager.yml.

- name: alert manager rules
  become: yes
  template:
    src: files/rules.yml
    dest: /etc/prometheus/rules.yml

- name: start alert manager as a service
  become: yes
  template:
    src: files/alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: configure systemd
  become: yes
  shell: |
    systemctl daemon-reload
    systemctl enable alertmanager
    systemctl start alertmanager
    systemctl restart prometheus
