- name: "install alert manager."
  unarchive:
    src: https://github.com/prometheus/alertmanager/releases/download/v0.24.0/alertmanager-0.24.0.linux-amd64.tar.gz
    dest: /
    remote_src: yes

- name: "add alertmanager's configuration."
  become: true
  template:
    src: "files/alertmanager.yml"
    dest: "/etc/prometheus/alertmanager.yml"

- name: "configure Alertmanager as a service."
  become: true
  copy:
    src: files/alertmanager.service
    dest: /etc/systemd/system/alertmanager.service

- name: "enable alertmanager service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: alertmanager
    enabled: yes

- name: "copy new rule for alerts."
  become: true
  copy:
    src: files/rules.yml
    dest: /etc/prometheus/rules.yml

- name: reload systemd
  become: yes
  shell: |
    systemctl restart prometheus
